services:
  - type: web
    name: devgauge-api
    env: node
    region: singapore
    plan: free
    buildCommand: "npm install && npx prisma generate && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false # Set securely in Render UI
      - key: JWT_SECRET
        sync: false # Set securely in Render UI
      - key: REDIS_URL
        sync: false # Set securely in Render UI
      - key: PORT
        value: 8000
